-- Additional data import (bookings, payments)

-- bookings
INSERT OR REPLACE INTO bookings (id, course_id, course_name, customer_name, customer_email, customer_phone, preferred_date, preferred_time, message, status, payment_status, amount, admin_note, created_at, updated_at) VALUES (6, '先生のためのai入門講座-授業で使える-基礎知識・活用事例・-mjvmmv4d', ' 先生のためのAI入門講座①：授業で使える！基礎知識・活用事例・セキュリティ対策', 'HIROKO tabata', 'hatarakusutairu@gmail.com', '08058287710', '2026-01-17', '10:00 - 12:00', NULL, 'confirmed', 'paid', 6000, NULL, '2026-01-02 10:49:55', '2026-01-02 11:51:03');

-- payments
INSERT OR REPLACE INTO payments (id, booking_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, payment_method, receipt_url, customer_email, customer_name, course_id, course_title, schedule_date, metadata, created_at, updated_at) VALUES (1, NULL, NULL, 'cs_test_a13kTIUYgfwMPk1P9DgEFGZP4YeoAktLY6JN9edA4nABjcUwCcMWZflGdT', 8000, 'jpy', 'pending', NULL, NULL, 'hatarakusutairu@gmail.com', 'HIROKO tabata', '初心者ok-aiで資格合格-プロンプト作成から学ぶ学習サポー-mju9buj1', '【初心者OK】AIで資格合格！プロンプト作成から学ぶ学習サポーター育成講座', NULL, '{"reservationId":3}', '2026-01-01 01:05:48', '2026-01-01 01:05:48');
INSERT OR REPLACE INTO payments (id, booking_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, payment_method, receipt_url, customer_email, customer_name, course_id, course_title, schedule_date, metadata, created_at, updated_at) VALUES (2, NULL, NULL, 'cs_test_a1OxviMhRrJmDkDgCDu99dwOqQsCzlhvcdQAXedvdV9TyiswxOcaYA8S5l', 6000, 'jpy', 'pending', NULL, NULL, 'hatarakusutairu@gmail.com', 'HIROKO tabata', '先生のためのai入門講座-授業で使える-基礎知識・活用事例・-mjvmmv4d', ' 先生のためのAI入門講座①：授業で使える！基礎知識・活用事例・セキュリティ対策', NULL, '{"reservationId":4}', '2026-01-02 09:22:49', '2026-01-02 09:22:49');
INSERT OR REPLACE INTO payments (id, booking_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, payment_method, receipt_url, customer_email, customer_name, course_id, course_title, schedule_date, metadata, created_at, updated_at) VALUES (3, NULL, 'pi_3Sl5tSRv2Wa0tJgz0T5R5y9i', 'cs_test_a1Mwd9DFmC9f4m6K7icNe89YxiDblCvaTPexoRsg14X0UmzeBni68IGb5D', 6000, 'jpy', 'succeeded', 'card', NULL, 'hatarakusutairu@gmail.com', 'HIROKO tabata', '先生のためのai入門講座-授業で使える-基礎知識・活用事例・-mjvmmv4d', ' 先生のためのAI入門講座①：授業で使える！基礎知識・活用事例・セキュリティ対策', NULL, '{"reservationId":5}', '2026-01-02 10:47:09', '2026-01-02 11:48:23');
INSERT OR REPLACE INTO payments (id, booking_id, stripe_payment_intent_id, stripe_checkout_session_id, amount, currency, status, payment_method, receipt_url, customer_email, customer_name, course_id, course_title, schedule_date, metadata, created_at, updated_at) VALUES (4, NULL, 'pi_3Sl5vqRv2Wa0tJgz0EUE6o58', 'cs_test_a1dKV0XefBV5FVRWszB0O9UitmwUTk3wsG0i9OJCWDzpSZTRf8f0nbTQSG', 6000, 'jpy', 'succeeded', 'card', NULL, 'hatarakusutairu@gmail.com', 'HIROKO tabata', '先生のためのai入門講座-授業で使える-基礎知識・活用事例・-mjvmmv4d', ' 先生のためのAI入門講座①：授業で使える！基礎知識・活用事例・セキュリティ対策', NULL, '{"reservationId":6}', '2026-01-02 10:49:56', '2026-01-02 11:51:03');
